# Generated by Django 4.1.1 on 2023-04-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='positions',
            table='Positions',
        ),
    ]
