# Generated by Django 4.1.1 on 2023-04-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_positions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='positions',
            table='positions',
        ),
    ]
