# Generated by Django 4.1.1 on 2023-04-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_positions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporterIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'transporter_intervention',
                'managed': False,
            },
        ),
    ]
